import pygame
import tile_map
#game variables
TILE_SIZE = 32
ROW_COUNT = 16
COLUMN_COUNT = ROW_COUNT
GAME_WIDTH = TILE_SIZE * COLUMN_COUNT
GAME_HEIGHT = TILE_SIZE * ROW_COUNT
GAME_MAP = tile_map.OPTIMIZED_GAME_MAP1

GAME_BGM_PATH = "music/game_music.mp3"
GAME_BGM_VOLUME = 0.45
GAME_FONT_PATH = "megaman-game-font.otf"

FPS = 60

HP_PER_SEGMENT = 20
MAX_SEGMENTS = 5

PLAYER_MAX_HEALTH = HP_PER_SEGMENT * MAX_SEGMENTS
HEALTH_SEGMENT_WIDTH = 25
HEALTH_SEGMENT_HEIGHT = 12

HEALTH_BAR_X = 40
HEALTH_BAR_Y = 40

#color
COLOR_BORDER = (0, 0, 0)
COLOR_EMPTY  = (120, 120, 120)   # xám – máu mất
COLOR_FILL   = (200, 50, 50)     # đỏ – máu còn
BORDER_THICKNESS = 1

#player variables

PLAYER_DISTANCE = 5

PLAYER_X = int(GAME_WIDTH/2)
PLAYER_Y = int(GAME_HEIGHT/2)
PLAYER_WIDTH = 48
PLAYER_HEIGHT = 54
PLAYER_JUMP_WIDTH = 52
PLAYER_JUMP_HEIGHT = 60
PLAYER_ATTACK_WIDTH = 58 #same height as PLAYER_HEIGHT
PLAYER_ATTACK_HEIGHT = PLAYER_ATTACK_WIDTH #same height as PLAYER_HEIGHT
# PLAYER_ATTACK_HEIGHT = 60

PLAYER_VELOCITY_X = 5
PLAYER_VELOCITY_Y = -11
GRAVITY = 0.5
FRICTION = 0.4

PLAYER_SHURIKEN_WIDTH = 16
PLAYER_SHURIKEN_HEIGHT = 12
PLAYER_SHURIKEN_VELOCITY_X = 5

#Custom event
INVINCIBLE_END = pygame.USEREVENT + 0
ATTACKING_END = pygame.USEREVENT + 1
SHOOTING_END = pygame.USEREVENT + 2
# FLOOR_Y = int(GAME_HEIGHT * 4/5)

#enemy variables
INFANTRYMAN_WIDTH = 28
METALL_WIDTH = 28
INFANTRYMAN_GUARD_HEIGHT = 28
INFANTRYMAN_GUARD_WIDTH = 30
INFANTRYMAN_HEIGHT = 55
METALL_HEIGHT = METALL_WIDTH
INFANTRYMAN_DAMAGE = 2 * HP_PER_SEGMENT
DRONE_DAMAGE = 2 * HP_PER_SEGMENT
METALL_DAMAGE = 1 * HP_PER_SEGMENT
ENEMY_BULLET_DAMAGE = 2 * HP_PER_SEGMENT
BOSS_CONTACT_DAMAGE = int(1.5 * HP_PER_SEGMENT)
INFANTRYMAN_VELOCITY_X = 2

INFANTRYMAN_BULLET_WIDTH = 12
INFANTRYMAN_BULLET_HEIGHT = INFANTRYMAN_BULLET_WIDTH
INFANTRYMAN_BULLET_WIDTH2 = 25
INFANTRYMAN_BULLET_HEIGHT2 = INFANTRYMAN_BULLET_WIDTH2
INFANTRYMAN_BULLET_VELOCITY_X = 2
INFANTRYMAN_BULLET_VELOCITY_Y = INFANTRYMAN_BULLET_VELOCITY_X
#item variables
LIFE_ENERGY_WIDTH = 15
LIFE_ENERGY_HEIGHT = 19
BIG_LIFE_ENERGY_WIDTH = 23
BIG_LIFE_ENERGY_HEIGHT = 27
KEY_ITEM_WIDTH = 18
KEY_ITEM_HEIGHT = 18
ITEM_VELOCITY_Y = -11 #items flies up first and gravity pulls it down

TIME_WARP_DURATION_MS = 4000
TIME_WARP_ENEMY_SPEED_MULTIPLIER = 0.5
TIME_WARP_MAX_CHARGES = 3

DRONE_WIDTH = 32
DRONE_HEIGHT = 40
DRONE_VELOCITY_X = 4
DRONE_VELOCITY_Y = 2

BOSS_WIDTH = 150
BOSS_HEIGHT = BOSS_WIDTH

WEB_WIDTH = 60
WEB_HEIGHT = WEB_WIDTH